### PR TITLE
Add orbat view to missions

### PR DESCRIPTION
**Pull request by TomBurch**
No fancy CSS, but sorts out all the needed data and displays the orbat
image
image
image

### CODE REVIEW

**Comment by Freddo3000** [comment]
How does it split sides and factions?

**Comment by TomBurch** [comment]
> How does it split sides and factions?

Physically splits it but doesn't give a name currently

**Comment by BorderKeeper** [comment]
Did you consider removing empty groups? Ie. Mikes, Gamblers, Etc.. in your original picture

**Review by Freddo3000 — CHANGES_REQUESTED** [review]
Needs something to split sides and factions. Does it support uploading missions with disabled/not set ORBAT? Missions without TMF settings present in SQM?

Ideally you'd also add mission icons, which should just be possible by converting all the ORBAT markers and putting them here, then referring to them: https://github.com/ARCOMM/ARCHUB/tree/master/public/images

I'd imagine there's some way to replace the dots with a custom image.

**Comment by TomBurch** [comment]
> Needs something to split sides and factions.

Working on this

> Does it support uploading missions with disabled/not set ORBAT? 

It doesn't attempt to display any mission with a `null` orbat (i.e. currently uploaded missions)
Please send me a PBO with a disabled ORBAT for testing

> Missions without TMF settings present in SQM?

Please send me a PBO with a disabled ORBAT for testing

>Ideally you'd also add mission icons

Any CSS styling should be done as follow-up work to this MR

**Comment by TomBurch** [comment]
Empty teams are removed:
image

Sides have titles:
image

**Review by BorderKeeper — APPROVED** [review]
lgtm

**Comment by TomBurch** [comment]
image

**Comment by BorderKeeper** [comment]
Was the migration locally tested? @TomBurch

**Comment by TomBurch** [comment]
@BorderKeeper Nope, no idea how they work. Want to walk me through it in VC?

**Comment by BorderKeeper** [comment]
Migration tested. Rollback not provided but is not needed, downgrade will work just fine.

**Pull request merged**
