### PR TITLE
#55 - upgrade laravel framework 5.5 -> 5.8

### PR DESCRIPTION
**Pull request by TomBurch**

### CODE REVIEW

**Comment by TomBurch** [comment]
# 5.5->5.6 necessary changes (https://laravel.com/docs/5.6/upgrade#upgrade-5.6.0)

image
image
image
image
image
image

**Comment by TomBurch** [comment]
# 5.6 -> 5.7 necessary changes (https://laravel.com/docs/5.7/upgrade#upgrade-5.7.0)

image
image
image
image

**Comment by TomBurch** [comment]
# 5.7 -> 5.8 necessary changes (https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0)

image
image
image

**Comment by TomBurch** [comment]
# 5.8 -> 6 necessary changes (https://laravel.com/docs/6.x/upgrade#upgrade-6.0)

image

**Comment by TomBurch** [comment]
Dependent on #67

**Review by BorderKeeper — APPROVED** [review]
lgtm

**Pull request merged**
